// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.asiainfo.yuwen.grpc.helloworld;

public final class HelloWorldProto {

    private HelloWorldProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface HelloRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:HelloRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         */
        java.lang.String getName();

        /**
         * <code>string name = 1;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

    }

    /**
     * <pre>
     * 方法请求,包含用户名
     * </pre>
     * <p>
     * Protobuf type {@code HelloRequest}
     */
    public static final class HelloRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:HelloRequest)
            HelloRequestOrBuilder {

        // Use HelloRequest.newBuilder() to construct.
        private HelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private HelloRequest() {
            name_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private HelloRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloRequest_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest.class, com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;

        /**
         * <code>string name = 1;</code>
         */
        @Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 1;</code>
         */
        @Override
        public com.google.protobuf.ByteString getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
              return true;
            }
            if (isInitialized == 0) {
              return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
              return size;
            }

            size = 0;
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest)) {
                return super.equals(obj);
            }
            com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest other = (com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest) obj;

            boolean result = true;
            result = result && getName()
                    .equals(other.getName());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 方法请求,包含用户名
         * </pre>
         * <p>
         * Protobuf type {@code HelloRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:HelloRequest)
                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequestOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloRequest_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest.class, com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest.Builder.class);
            }

            // Construct using com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                name_ = "";

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloRequest_descriptor;
            }

            @Override
            public com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest getDefaultInstanceForType() {
                return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest.getDefaultInstance();
            }

            @Override
            public com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest build() {
                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest buildPartial() {
                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest result = new com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest(this);
                result.name_ = name_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest) {
                    return mergeFrom((com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest other) {
                if (other == com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest.getDefaultInstance()) {
                  return this;
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>string name = 1;</code>
             */
            @Override
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             */
            @Override
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:HelloRequest)
        }

        // @@protoc_insertion_point(class_scope:HelloRequest)
        private static final com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest();
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<HelloRequest>
                PARSER = new com.google.protobuf.AbstractParser<HelloRequest>() {
            public HelloRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new HelloRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<HelloRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<HelloRequest> getParserForType() {
            return PARSER;
        }

        public com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface HelloReplyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:HelloReply)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string message = 1;</code>
         */
        java.lang.String getMessage();

        /**
         * <code>string message = 1;</code>
         */
        com.google.protobuf.ByteString
        getMessageBytes();

    }

    /**
     * <pre>
     * 方法响应,包含响应的消息
     * </pre>
     * <p>
     * Protobuf type {@code HelloReply}
     */
    public static final class HelloReply extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:HelloReply)
            HelloReplyOrBuilder {

        // Use HelloReply.newBuilder() to construct.
        private HelloReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private HelloReply() {
            message_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private HelloReply(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            message_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloReply_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloReply_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply.class, com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply.Builder.class);
        }

        public static final int MESSAGE_FIELD_NUMBER = 1;
        private volatile java.lang.Object message_;

        /**
         * <code>string message = 1;</code>
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <code>string message = 1;</code>
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getMessageBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getMessageBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply)) {
                return super.equals(obj);
            }
            com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply other = (com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply) obj;

            boolean result = true;
            result = result && getMessage()
                    .equals(other.getMessage());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 方法响应,包含响应的消息
         * </pre>
         * <p>
         * Protobuf type {@code HelloReply}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:HelloReply)
                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReplyOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloReply_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloReply_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply.class, com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply.Builder.class);
            }

            // Construct using com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                message_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.internal_static_HelloReply_descriptor;
            }

            public com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply getDefaultInstanceForType() {
                return com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply.getDefaultInstance();
            }

            public com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply build() {
                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply buildPartial() {
                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply result = new com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply(this);
                result.message_ = message_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply) {
                    return mergeFrom((com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply other) {
                if (other == com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply.getDefaultInstance())
                    return this;
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object message_ = "";

            /**
             * <code>string message = 1;</code>
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string message = 1;</code>
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string message = 1;</code>
             */
            public Builder setMessage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 1;</code>
             */
            public Builder clearMessage() {

                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>string message = 1;</code>
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                message_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:HelloReply)
        }

        // @@protoc_insertion_point(class_scope:HelloReply)
        private static final com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply();
        }

        public static com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<HelloReply>
                PARSER = new com.google.protobuf.AbstractParser<HelloReply>() {
            public HelloReply parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new HelloReply(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<HelloReply> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<HelloReply> getParserForType() {
            return PARSER;
        }

        @Override
        public com.asiainfo.yuwen.grpc.helloworld.HelloWorldProto.HelloReply getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_HelloRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_HelloRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_HelloReply_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_HelloReply_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020helloworld.proto\"\034\n\014HelloRequest\022\014\n\004na" +
                        "me\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t2" +
                        "b\n\007Greeter\022(\n\010SayHello\022\r.HelloRequest\032\013." +
                        "HelloReply\"\000\022-\n\rSayHelloAgain\022\r.HelloReq" +
                        "uest\032\013.HelloReply\"\000B7\n\"com.asiainfo.yuwe" +
                        "n.grpc.helloworldB\017HelloWorldProtoP\000b\006pr" +
                        "oto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    @Override
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_HelloRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_HelloRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_HelloRequest_descriptor,
                new java.lang.String[]{"Name",});
        internal_static_HelloReply_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_HelloReply_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_HelloReply_descriptor,
                new java.lang.String[]{"Message",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
